//
//  UIDevice+TalkingDataExtension.h
//  TalkingData
//
//  Created by Elf Sundae on 2022/03/09.
//  Copyright © 2022 https://0x123.com. All rights reserved.
//

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface UIDevice (TalkingDataExtension)

/**
 * Returns the device identifier generated by TalkingData.
 */
- (NSString *)talkingDataDeviceIdentifier;

@end

NS_ASSUME_NONNULL_END
