name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pod install

      - name: Build Example Project
        run: |
          xcodebuild clean build \
            -workspace TalkingData.xcworkspace \
            -scheme Example \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 13 Pro' \
            | xcpretty

      - name: Lint Pod
        run: pod lib lint --allow-warnings --skip-import-validation
